replicaCount: 1
deploymentName: helloworld
namespace: helloworld

image:
  repository: registry.registry.svc.cluster.local:5000/helloworld
  tag: latest
  pullPolicy: Always

hosts:
  - helloworld.gmk.lan
  - helloworld.tp.lan

service:
  port: 8080

istio:
  gateway: helloworld-gateway

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: helloworld-tls

extraVolumeMounts: []
extraVolumes: []
extraEnv: []
