apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: helloworld-run-
  labels:
    app.kubernetes.io/name: helloworld
spec:
  pipelineRef:
    name: helloworld-pipeline

  taskRunTemplate:
    serviceAccountName: helloworld-pipeline-sa

  params:
    - name: repo-url
      value: https://github.com/wlanboy/helm-for-java-devs.git
    - name: revision
      value: main
    - name: image
      value: registry.registry.svc.cluster.local:5000/helloworld:latest
    - name: dockerfile
      value: java/Dockerfile

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

  timeouts:
    pipeline: 1h0m0s
