apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploymentName }}-config
data:
  application.properties: |
    spring.application.name={{ .Values.deploymentName }}
    management.endpoints.web.exposure.include=prometheus,health,info
    management.endpoint.health.show-details=always
