{{- if and .Values.mysql.external.tls.enabled .Values.mysql.external.tls.createCaSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.external.tls.credentialName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Istio erwartet den Key "cacert" für TLS-Origination mit credentialName.
  cacert: {{ .Files.Get "ca/ca-gmk.pem" | b64enc }}
{{- end }}
