spring.application.name={{ .Values.deploymentName }}
server.port={{ .Values.service.port }}
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always
logging.structured.format.console={{ .Values.logging.structured.format }}
